import { useEffect, useMemo, useRef, useState } from 'react'
import './App.css'

type Status = 'PENDIENTE' | 'HECHO' | 'ARCHIVADO'
type View = 'board' | 'today' | 'reminders' | 'calendar' | 'done'
type Note = { id:string;text:string;description?:string;status:Status;date?:string;time?:string;category:string;priority:string;color:string;pinned:boolean;x:number;y:number;width:number;height:number;createdAt:string;completedAt?:string }
const today=new Date().toISOString().slice(0,10), tomorrow=new Date(Date.now()+864e5).toISOString().slice(0,10), yesterday=new Date(Date.now()-864e5).toISOString().slice(0,10)
const seed:Note[]=[
{id:'1',text:'Revisar resultados SSI',status:'PENDIENTE',date:today,time:'15:00',category:'Ventas',priority:'ALTA',color:'yellow',pinned:true,x:100,y:95,width:255,height:150,createdAt:today},
{id:'2',text:'Validar tiempos de gestoría',status:'PENDIENTE',date:today,category:'Calidad',priority:'NORMAL',color:'blue',pinned:false,x:440,y:210,width:255,height:145,createdAt:today},
{id:'3',text:'Hablar con Marcelo por reclamo',status:'PENDIENTE',date:yesterday,category:'Postventa',priority:'URGENTE',color:'rose',pinned:false,x:750,y:100,width:260,height:155,createdAt:yesterday},
{id:'4',text:'IDEA: mejorar mapa de procesos',status:'PENDIENTE',category:'Ideas',priority:'BAJA',color:'violet',pinned:false,x:240,y:455,width:260,height:144,createdAt:today},
{id:'5',text:'Actualizar procedimiento',status:'HECHO',date:today,category:'Calidad',priority:'NORMAL',color:'green',pinned:false,x:635,y:425,width:250,height:145,createdAt:today,completedAt:today}]
const overdue=(n:Note)=>n.status==='PENDIENTE'&&!!n.date&&n.date<today
const label=(d?:string)=>!d?'Sin fecha':d===today?'Hoy':d===tomorrow?'Mañana':new Intl.DateTimeFormat('es-AR',{day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'))
const apiUrl=import.meta.env.VITE_GOOGLE_SCRIPT_URL as string|undefined
const remote=(action:string,id?:string,data?:unknown)=>!apiUrl?Promise.resolve():fetch(apiUrl,{method:'POST',body:JSON.stringify({action,id,data})}).then(r=>r.json()).then(r=>{if(!r.success)throw Error(r.error||'Error de sincronización')})
const toSheet=(n:Partial<Note>)=>Object.fromEntries(Object.entries(n).map(([k,v])=>[{id:'ID',text:'TEXTO',description:'DESCRIPCION',status:'ESTADO',date:'FECHA',time:'HORA',category:'CATEGORIA',priority:'PRIORIDAD',color:'COLOR',pinned:'FIJADA',x:'X',y:'Y',width:'ANCHO',height:'ALTO',createdAt:'CREADO_EN',completedAt:'COMPLETADO_EN'}[k]||k.toUpperCase(),v]))
const fromSheet=(n:any):Note=>({id:n.ID,text:n.TEXTO||'',description:n.DESCRIPCION||'',status:n.ESTADO||'PENDIENTE',date:n.FECHA||undefined,time:n.HORA||undefined,category:n.CATEGORIA||'General',priority:n.PRIORIDAD||'NORMAL',color:n.COLOR||'yellow',pinned:n.FIJADA===true||n.FIJADA==='TRUE',x:Number(n.X)||120,y:Number(n.Y)||120,width:Number(n.ANCHO)||255,height:Number(n.ALTO)||145,createdAt:n.CREADO_EN||new Date().toISOString(),completedAt:n.COMPLETADO_EN||undefined})

export default function App(){
 const [notes,setNotes]=useState<Note[]>(()=>JSON.parse(localStorage.getItem('mi-tablero-notes')||'null')??seed),[view,setView]=useState<View>('board'),[filter,setFilter]=useState('Todos'),[selected,setSelected]=useState<Note|null>(null),[composer,setComposer]=useState(false),[palette,setPalette]=useState(false),[query,setQuery]=useState('');const board=useRef<HTMLDivElement>(null)
 useEffect(()=>localStorage.setItem('mi-tablero-notes',JSON.stringify(notes)),[notes]);useEffect(()=>{if(apiUrl)fetch(`${apiUrl}?action=getNotes`).then(r=>r.json()).then(r=>r.success&&setNotes(r.data.map(fromSheet))).catch(()=>console.warn('No se pudo cargar Google Sheets; se usa el cache local'))},[]);useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();setComposer(true)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(true)}if(e.key==='Escape'){setSelected(null);setPalette(false);setComposer(false)}};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[])
 const update=(id:string,data:Partial<Note>)=>{setNotes(x=>x.map(n=>n.id===id?{...n,...data}:n));void remote('updateNote',id,toSheet(data)).catch(()=>console.warn('Error de sincronización'))};const create=(text:string,date?:string)=>{if(!text.trim())return;const r=board.current?.getBoundingClientRect();const n:Note={id:crypto.randomUUID(),text:text.trim(),status:'PENDIENTE',date,category:'General',priority:'NORMAL',color:'yellow',pinned:false,x:Math.max(70,(r?.width||800)/2-120),y:Math.max(70,(r?.height||600)/2-70),width:255,height:145,createdAt:new Date().toISOString()};setNotes(x=>[...x,n]);void remote('createNote',undefined,toSheet(n)).catch(()=>console.warn('Error de sincronización'));setComposer(false);setSelected(n)}
 const pending=notes.filter(n=>n.status==='PENDIENTE');const shown=useMemo(()=>notes.filter(n=>filter==='Pendientes'?n.status==='PENDIENTE':filter==='Hoy'?n.status==='PENDIENTE'&&n.date===today:filter==='Vencidos'?overdue(n):filter==='Fijadas'?n.pinned:filter==='Hechos'?n.status==='HECHO':n.status!=='ARCHIVADO').filter(n=>!query||(`${n.text} ${n.category}`).toLowerCase().includes(query.toLowerCase())),[notes,filter,query])
 const nav:[[View,string,string],...any[]]=[['board','▦','Pizarrón'],['today','☀','Mi día'],['reminders','✓','Recordatorios'],['calendar','□','Calendario'],['done','↻','Hechos']]
 return <div className="app"><aside className="sidebar"><div className="brand"><b>M</b><span>Mi Tablero</span></div><nav>{nav.map(([v,i,t])=><button className={view===v?'active':''} onClick={()=>setView(v)} key={v}><i>{i}</i>{t}{v==='reminders'&&<em>{pending.length}</em>}</button>)}</nav><small className="sect">CATEGORÍAS</small>{['General','Calidad','Ventas','Postventa','Personal','Ideas'].map(c=><button className="cat" onClick={()=>{setView('board');setQuery(c)}} key={c}><span/> {c}</button>)}<footer>⚙ Configuración<br/><small>✓ Guardado</small></footer></aside><main><header><button className="search" onClick={()=>setPalette(true)}>⌕ <span>Buscar notas, comandos…</span><kbd>Ctrl K</kbd></button><button className="new" onClick={()=>setComposer(true)}>＋ Nueva nota</button></header>
 {view==='board'&&<Board notes={shown} filter={filter} setFilter={setFilter} counts={[pending.length,pending.filter(n=>n.date===today).length,pending.filter(overdue).length]} update={update} select={setSelected} boardRef={board}/>} {view==='today'&&<List title="Mi día" subtitle="Lo que merece tu atención ahora." notes={pending.filter(n=>overdue(n)||n.date===today)} update={update} select={setSelected} grouped/>}{view==='reminders'&&<Reminders notes={pending} update={update} select={setSelected}/>} {view==='done'&&<List title="Hechos" subtitle="Todo lo que ya resolviste." notes={notes.filter(n=>n.status==='HECHO')} update={update} select={setSelected}/>} {view==='calendar'&&<Calendar notes={notes} select={setSelected}/>}</main>{composer&&<Composer close={()=>setComposer(false)} create={create}/>} {palette&&<Palette notes={notes} close={()=>setPalette(false)} select={setSelected} go={(v:View)=>{setView(v);setPalette(false)}}/>}{selected&&<Detail note={notes.find(n=>n.id===selected.id)||selected} update={update} close={()=>setSelected(null)}/>}</div>
}
const Board=({notes,filter,setFilter,counts,update,select,boardRef}:any)=><section className="board-page"><div className="toolbar">{['Todos','Pendientes','Hoy','Vencidos','Fijadas','Hechos'].map((x,i)=><button className={filter===x?'chosen':''} onClick={()=>setFilter(x)} key={x}>{x}{i>0&&i<4?` ${counts[i-1]}`:''}</button>)}<span>−　100%　+</span></div><div className="board" ref={boardRef}>{notes.length?notes.map((n:Note)=><Card note={n} update={update} select={select} key={n.id}/>):<div className="empty"><h2>Tu pizarrón está vacío</h2><p>Escribí algo que quieras recordar.</p></div>}</div></section>
function Card({note,update,select}:any){const start=useRef<any>(null);const down=(e:React.PointerEvent)=>{if((e.target as HTMLElement).closest('button'))return;start.current={x:e.clientX,y:e.clientY,l:note.x,t:note.y};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)};const move=(e:React.PointerEvent)=>start.current&&update(note.id,{x:Math.max(0,start.current.l+e.clientX-start.current.x),y:Math.max(0,start.current.t+e.clientY-start.current.y)});return <article className={`card ${note.color} ${note.status==='HECHO'?'done':''}`} style={{left:note.x,top:note.y,width:note.width,minHeight:note.height}} onPointerDown={down} onPointerMove={move} onPointerUp={()=>start.current=null} onDoubleClick={()=>select(note)}><div className="cardtop"><b className={note.priority}/>{note.category}{note.pinned&&<i>⌖</i>}</div><h3>{note.text}</h3><p>{overdue(note)?'Vencida':label(note.date)}{note.time&&` · ${note.time}`}</p><div className="actions"><button onClick={()=>update(note.id,{status:note.status==='HECHO'?'PENDIENTE':'HECHO',completedAt:new Date().toISOString()})}>{note.status==='HECHO'?'↻ Reabrir':'✓ Hecho'}</button><button onClick={()=>select(note)}>•••</button></div></article>}
function List({title,subtitle,notes,update,select,grouped}:any){const late=notes.filter(overdue),rest=notes.filter((n:Note)=>!overdue(n));return <section className="list"><div className="heading"><p>{subtitle}</p><h1>{title}</h1></div>{grouped&&<NoteList title="Vencidos" notes={late} update={update} select={select}/>}<NoteList title={grouped?'Hoy':''} notes={rest} update={update} select={select}/></section>}
function NoteList({title,notes,update,select}:any){return <div className="note-list">{title&&<h2>{title}<small>{notes.length}</small></h2>}{notes.length?notes.map((n:Note)=><div className="rem" key={n.id}><button className={`check ${n.status==='HECHO'?'checked':''}`} onClick={()=>update(n.id,{status:n.status==='HECHO'?'PENDIENTE':'HECHO',completedAt:new Date().toISOString()})}>✓</button><button className="remtext" onClick={()=>select(n)}><b>{n.text}</b><span>{overdue(n)?'Vencida · ':''}{label(n.date)}{n.time&&` · ${n.time}`}　{i(n.category)}</span></button><button className="postpone" onClick={()=>update(n.id,{date:tomorrow})}>Posponer</button></div>):<p className="nothing">No hay notas aquí.</p>}</div>};const i=(x:string)=><i>{x}</i>
function Reminders({notes,update,select}:any){return <section className="list"><div className="heading"><p>{notes.length} pendientes · {notes.filter(overdue).length} vencidas</p><h1>Mis recordatorios</h1></div>{[['Vencidos',notes.filter(overdue)],['Hoy',notes.filter((n:Note)=>n.date===today)],['Mañana',notes.filter((n:Note)=>n.date===tomorrow)],['Sin fecha',notes.filter((n:Note)=>!n.date)]].map(([t,ns]:any)=><NoteList title={t} notes={ns} update={update} select={select} key={t}/>)}</section>}
function Calendar({notes,select}:any){const d=new Date(),start=new Date(d.getFullYear(),d.getMonth(),1).getDay(),days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();return <section className="calendar"><div className="heading"><p>Vista mensual</p><h1>{new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric'}).format(d)}</h1></div><div className="calhead">{['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'].map(x=><span key={x}>{x}</span>)}</div><div className="grid">{Array.from({length:start},(_,i)=><div key={'b'+i}/>)}{Array.from({length:days},(_,i)=>{const day=i+1,ds=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,a=notes.filter((n:Note)=>n.date===ds);return <div className={ds===today?'now':''} key={day}><b>{day}</b>{a.slice(0,3).map((n:Note)=><button onClick={()=>select(n)} key={n.id}>{n.text}</button>)}</div>})}</div></section>}
function Composer({close,create}:any){const[text,setText]=useState(''),[date,setDate]=useState<string|undefined>();return <div className="overlay"><form className="composer" onSubmit={e=>{e.preventDefault();create(text,date)}}><button type="button" className="x" onClick={close}>×</button><small>NUEVA NOTA</small><input autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="¿Qué querés recordar?"/><div><button type="button" onClick={()=>setDate(today)}>Hoy</button><button type="button" onClick={()=>setDate(tomorrow)}>Mañana</button><button className="new" type="submit">Crear nota ↵</button></div></form></div>}
function Palette({notes,close,select,go}:any){const[q,setQ]=useState('');const hits=notes.filter((n:Note)=>`${n.text} ${n.category} ${n.description||''}`.toLowerCase().includes(q.toLowerCase())).slice(0,5);return <div className="overlay"><div className="palette"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar una nota o comando…"/><small>IR A</small>{[['board','Pizarrón'],['reminders','Recordatorios'],['calendar','Calendario'],['done','Hechos']].map(([v,l])=><button onClick={()=>go(v)} key={v}>{l}</button>)}{hits.length>0&&<><small>NOTAS</small>{hits.map((n:Note)=><button onClick={()=>{select(n);close()}} key={n.id}>{n.text}<i>{n.category}</i></button>)}</>}<button className="closepal" onClick={close}>Cerrar</button></div></div>}
function Detail({note,update,close}:any){const[f,setF]=useState(note);useEffect(()=>setF(note),[note]);const save=(x:any)=>{setF((old:any)=>({...old,...x}));update(note.id,x)};return <aside className="detail"><button className="x" onClick={close}>×</button><small>NOTA</small><textarea value={f.text} onChange={e=>save({text:e.target.value})}/><textarea className="desc" placeholder="Agregá una descripción…" value={f.description||''} onChange={e=>save({description:e.target.value})}/><label>Fecha<input type="date" value={f.date||''} onChange={e=>save({date:e.target.value||undefined})}/></label><label>Hora<input type="time" value={f.time||''} onChange={e=>save({time:e.target.value||undefined})}/></label><label>Categoría<select value={f.category} onChange={e=>save({category:e.target.value})}>{['General','Calidad','Ventas','Postventa','Personal','Ideas'].map(x=><option key={x}>{x}</option>)}</select></label><label>Prioridad<select value={f.priority} onChange={e=>save({priority:e.target.value})}>{['BAJA','NORMAL','ALTA','URGENTE'].map(x=><option key={x}>{x}</option>)}</select></label><div className="colors">{['yellow','blue','green','rose','violet'].map(c=><button className={c} onClick={()=>save({color:c})} key={c}/>)}</div><button className="complete" onClick={()=>save({status:f.status==='HECHO'?'PENDIENTE':'HECHO',completedAt:new Date().toISOString()})}>{f.status==='HECHO'?'↻ Reabrir nota':'✓ Marcar como hecha'}</button></aside>}
